services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=mongodb://mongo:27017/mercadomio
      - REDIS_URI=redis://redis:6379
    env_file:
      - ./backend/.env
    depends_on:
      - mongo
      - redis
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/mongo/db
  postgres:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: admin123
      POSTGRES_USER: admin
      POSTGRES_DB: mercadomio
    volumes:
      - postgres_data:/data/postgresql/db
    ports:
      - "5432:5432"
  redis:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
      - "8001:8001" # RedisInsight
    volumes:
      - redis_data:/data/redis/db
  directus:
    image: directus/directus:latest
    ports:
      - "8055:8055"
    environment:
      - KEY=mercadomio
      - SECRET=supersecretkey
      - DB_CLIENT=pg
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=mercadomio
      - DB_USER=admin
      - DB_PASSWORD=admin123
      - ADMIN_EMAIL=admin@mercadomio.mx
      - ADMIN_PASSWORD=admin123
      - CORS_ENABLED=true
      - CORS_ORIGIN="*"
      - CORS_CREDENTIALS=true
      - CORS_METHODS=GET,POST,PATCH,DELETE
      - CORS_ALLOWED_HEADERS=Content-Type,Authorization
      - FILES_PUBLIC_ACCESS=true
      - PUBLIC_URL=http://192.168.1.216:8055
      - ASSETS_REQUIRE_AUTHENTICATION=false
      - ASSETS_CACHE_TTL=30d
    depends_on:
      - postgres
volumes:
  mongo_data: 
  postgres_data:
  redis_data:
