name: mercadomio

services:
  backend:
    build: ../backend
    ports:
      - "5200:8080"
    environment:
      - MONGO_URI=mongodb://mongo:27017/mercadomio
      - REDIS_URI=redis://redis:6379
      - USERBREW_ISSUER=${USERBREW_ISSUER:-http://localhost:8090}
      - USERBREW_DISCOVERY_URL=${USERBREW_DISCOVERY_URL:-http://localhost:8090/.well-known/openid-configuration}
      - IMGVAULT_URL=http://imgvault-server:8081
      - IMGVAULT_API_KEY="REDACTED"
    env_file:
      - path: ../backend/.env
        required: false
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - default

  frontend:
    build: ../frontend
    ports:
      - "5201:80"
    depends_on:
      - backend

  mongo:
    image: mongo:7
    ports:
      - "5211:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 10s
      retries: 5

  redis:
    image: redis/redis-stack:latest
    ports:
      - "5212:6379"
      - "5213:8001" # RedisInsight
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongo_data:
  redis_data:
