name: mercadomio-qa

services:
  backend:
    build: ../backend
    ports:
      - "5220:8080"
    environment:
      - MONGO_URI=mongodb://mongo:27017/mercadomio
      - REDIS_URI=redis://redis:6379
    env_file:
      - path: ../backend/.env
        required: false
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_healthy

  frontend:
    build: ../frontend
    ports:
      - "5221:80"
    depends_on:
      - backend

  mongo:
    image: mongo:7
    ports:
      - "5211:27017"
    volumes:
      - qa_mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 10s
      retries: 5

  redis:
    image: redis/redis-stack:latest
    ports:
      - "5212:6379"
      - "5213:8001" # RedisInsight
    volumes:
      - qa_redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  qa_mongo_data:
  qa_redis_data: